# Generated by Django 6.0.2 on 2026-02-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio_title', models.CharField(help_text='Ex: Desenvolvedor Fullstack & Designer UI/UX', max_length=200)),
                ('bio_description', models.TextField(help_text='Uma descrição breve para a seção Hero')),
                ('about_me', models.TextField(help_text='Descrição completa sobre você')),
                ('experiences', models.TextField(help_text='O que você já fez/mexeu')),
                ('interests', models.TextField(help_text='No que tem interesse em trabalhar')),
                ('currently_developing', models.CharField(help_text='O que está desenvolvendo agora', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
