# Generated by Django 6.0.2 on 2026-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(help_text='Classe FontAwesome. Ex: fab fa-python', max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('embedded', 'Sistemas Embarcados'), ('tools', 'Ferramentas & Hardware')], max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='Porcentagem de 0 a 100')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['order', 'name'],
            },
        ),
    ]
