# Generated by Django 6.0.2 on 2026-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Desenvolvedor Junior ou Ciência da Computação', max_length=100)),
                ('organization', models.CharField(help_text='Empresa ou Instituição', max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(help_text='Ex: Jan 2023 - Presente', max_length=50)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('work', 'Experiência Profissional'), ('education', 'Formação Acadêmica')], default='work', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item da Linha do Tempo',
                'verbose_name_plural': 'Itens da Linha do Tempo',
                'ordering': ['order', '-id'],
            },
        ),
    ]
