<<<<<<< HEAD
# Generated by Django 5.2.11 on 2026-02-26 04:34
=======
# Generated by Django 6.0.2 on 2026-08-13 20:09
>>>>>>> e01554ae2930db3f7cb4678ff178dd88dcf5f891

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_timelineitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='timelineitem',
            options={'ordering': ['item_type', 'order', '-id'], 'verbose_name': 'Item da Linha do Tempo', 'verbose_name_plural': 'Itens da Linha do Tempo'},
        ),
    ]
